class AddHolesToCourse < ActiveRecord::Migration
  def change
  	add_column :courses, :h1_yds, :integer
  	add_column :courses, :h2_yds, :integer
  	add_column :courses, :h3_yds, :integer
  	add_column :courses, :h4_yds, :integer
  	add_column :courses, :h5_yds, :integer
  	add_column :courses, :h6_yds, :integer
  	add_column :courses, :h7_yds, :integer
  	add_column :courses, :h8_yds, :integer
  	add_column :courses, :h9_yds, :integer
  	add_column :courses, :h10_yds, :integer
  	add_column :courses, :h11_yds, :integer
  	add_column :courses, :h12_yds, :integer
  	add_column :courses, :h13_yds, :integer
  	add_column :courses, :h14_yds, :integer
  	add_column :courses, :h15_yds, :integer
  	add_column :courses, :h16_yds, :integer
  	add_column :courses, :h17_yds, :integer
  	add_column :courses, :h18_yds, :integer
  	add_column :courses, :h1_par, :integer
  	add_column :courses, :h2_par, :integer
  	add_column :courses, :h3_par, :integer
  	add_column :courses, :h4_par, :integer
  	add_column :courses, :h5_par, :integer
  	add_column :courses, :h6_par, :integer
  	add_column :courses, :h7_par, :integer
  	add_column :courses, :h8_par, :integer
  	add_column :courses, :h9_par, :integer
  	add_column :courses, :h10_par, :integer
  	add_column :courses, :h11_par, :integer
  	add_column :courses, :h12_par, :integer
  	add_column :courses, :h13_par, :integer
  	add_column :courses, :h14_par, :integer
  	add_column :courses, :h15_par, :integer
  	add_column :courses, :h16_par, :integer
  	add_column :courses, :h17_par, :integer
  	add_column :courses, :h18_par, :integer
		add_column :courses, :h1_hcap, :integer
  	add_column :courses, :h2_hcap, :integer
  	add_column :courses, :h3_hcap, :integer
  	add_column :courses, :h4_hcap, :integer
  	add_column :courses, :h5_hcap, :integer
  	add_column :courses, :h6_hcap, :integer
  	add_column :courses, :h7_hcap, :integer
  	add_column :courses, :h8_hcap, :integer
  	add_column :courses, :h9_hcap, :integer
  	add_column :courses, :h10_hcap, :integer
  	add_column :courses, :h11_hcap, :integer
  	add_column :courses, :h12_hcap, :integer
  	add_column :courses, :h13_hcap, :integer
  	add_column :courses, :h14_hcap, :integer
  	add_column :courses, :h15_hcap, :integer
  	add_column :courses, :h16_hcap, :integer
  	add_column :courses, :h17_hcap, :integer
  	add_column :courses, :h18_hcap, :integer
  	add_column :courses, :out_yds, :integer
  	add_column :courses, :in_yds, :integer
  	add_column :courses, :out_par, :integer
  	add_column :courses, :in_par, :integer
  end
end
