class AddShotsAndPuttsToRound < ActiveRecord::Migration
  def change
  	add_column :rounds, :s1, :integer
  	add_column :rounds, :s2, :integer
  	add_column :rounds, :s3, :integer
  	add_column :rounds, :s4, :integer
  	add_column :rounds, :s5, :integer
  	add_column :rounds, :s6, :integer
  	add_column :rounds, :s7, :integer
  	add_column :rounds, :s8, :integer
  	add_column :rounds, :s9, :integer
  	add_column :rounds, :s10, :integer
  	add_column :rounds, :s11, :integer
  	add_column :rounds, :s12, :integer
  	add_column :rounds, :s13, :integer
  	add_column :rounds, :s14, :integer
  	add_column :rounds, :s15, :integer
  	add_column :rounds, :s16, :integer
  	add_column :rounds, :s17, :integer
  	add_column :rounds, :s18, :integer
  	add_column :rounds, :p1, :integer
  	add_column :rounds, :p2, :integer
  	add_column :rounds, :p3, :integer
  	add_column :rounds, :p4, :integer
  	add_column :rounds, :p5, :integer
  	add_column :rounds, :p6, :integer
  	add_column :rounds, :p7, :integer
  	add_column :rounds, :p8, :integer
  	add_column :rounds, :p9, :integer
  	add_column :rounds, :p10, :integer
  	add_column :rounds, :p11, :integer
  	add_column :rounds, :p12, :integer
  	add_column :rounds, :p13, :integer
  	add_column :rounds, :p14, :integer
  	add_column :rounds, :p15, :integer
  	add_column :rounds, :p16, :integer
  	add_column :rounds, :p17, :integer
  	add_column :rounds, :p18, :integer
  end
end
